apiVersion: 1

datasources:
  - name: ClickHouse Traces
    uid: clickhouse-traces
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      host: host.docker.internal
      port: 8123
      protocol: http
      secure: false
      username: otel
      defaultDatabase: otel
      defaultTable: otel_traces
      dialTimeout: 10
      queryTimeout: 60
      validateSql: false
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
        durationUnit: nanoseconds
        traceIdColumn: TraceId
        spanIdColumn: SpanId
        parentSpanIdColumn: ParentSpanId
        serviceNameColumn: ServiceName
        operationNameColumn: SpanName
        startTimeColumn: Timestamp
        durationColumn: Duration
    secureJsonData:
      password: otel
